"@startuml entities_relationship"

' !define ENTITY
!define PRIMARY_KEY(x) <b><color:blue>x</color></b>
!define FOREIGN_KEY(x) <color:green>x</color>

hide circle
left to right direction

' ---> T_DEMANDA parent relationship
entity T_DEMANDA {
    + PRIMARY_KEY(id)
    --
    --
    FOREIGN_KEY(NNyA_principal)
    FOREIGN_KEY(VULNERACION_principal)
    --
}
T_DEMANDA_ASIGNADO "*" - "1" T_USER
T_DEMANDA "1" - "*" T_DEMANDA_ASIGNADO
T_DEMANDA "1" -- "1" T_PRECALIFICACION_DEMANDA
T_PRECALIFICACION_DEMANDA "*" -- "1" T_ESTADO_DEMANDA

T_DEMANDA "*" -- "1" T_LOCALIZACION
T_LOCALIZACION "*" -- "1" T_BARRIO
T_LOCALIZACION "*" -- "1" T_LOCALIDAD
T_LOCALIZACION "*" -- "1" T_PROVINCIA

T_DEMANDA_NNyA "*" - "1" T_DEMANDA
T_NNyA "1" - "*" T_DEMANDA_NNyA

T_NNyA "1" -- "1" T_NNyA_EDUCACION
T_NNyA_EDUCACION "*" -- "1" T_INSTITUCION_EDUCATIVA
T_NNyA "*" -- "1" T_INSTITUCION_SANITARIA

T_NNyA "1" - "1" T_PERSONA

T_DEMANDA_PERSONA_CONVIVIENTE "*" -- "1" T_DEMANDA
T_PERSONA "1" -- "*" T_DEMANDA_PERSONA_CONVIVIENTE

T_VINCULO_PERSONA "*" - "1" T_PERSONA
T_VINCULO_PERSONA "*" - "1" T_PERSONA
T_VINCULO "1" --- "*" T_VINCULO_PERSONA

T_DEMANDA_AUTORDV "*" -- "1" T_DEMANDA
T_PERSONA "1" -- "*" T_DEMANDA_AUTORDV

T_DEMANDA "*" -- "1" T_USUARIO_LINEA
T_USUARIO_LINEA "*" -- "1" T_VINCULO_USUARIO_LINEA

T_USUARIO_LINEA "*" -- "1" T_INSTITUCION_USUARIO_LINEA

T_USUARIO_LINEA "*" -- "1" T_RESPONSABLE
T_RESPONSABLE "*" -- "1" T_CARGO

T_DEMANDA "1" --- "*" T_VULNERACION
T_DDV "1" -- "*" T_VULNERACION

T_VULNERACION "*" -- "1" T_PRIORIDAD_INTERVENCION
T_VULNERACION "*" -- "1" T_PROBLEMATICA_IDENTIFICADA
T_VULNERACION "*" -- "1" T_AMBITO_VULNERACION

T_VULNERACION "*" -- "1" T_OPERADOR
T_NNyA "1" -- "*" T_VULNERACION

T_ACTIVIDAD "*" ---- "1" T_DEMANDA
T_ACTIVIDAD "*" - "1" T_ACTIVIDAD_TIPO
T_ACTIVIDAD "*" - "1" T_INSTITUCION_ACTIVIDAD

T_RESPUESTA "*" -- "1" T_DEMANDA
T_RESPUESTA "*" - "1" T_INSTITUCION_RESPUESTA

T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA
T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA

T_EVALUACION "*" --- "1" T_DEMANDA
T_EVALUACION "1" -- "*" T_VALIDACION_DATOS
T_EVALUACION "1" -- "*" T_ACTIVIDADES_REGISTRADAS
T_EVALUACION "1" -- "*" T_VALORACIONES
T_EVALUACION "1" -- "*" T_ACCIONES_NECESARIAS

T_LEGAJO "1" - "1" T_NNyA

T_LEGAJO_ASIGNADO "*" - "1" T_USER
T_LEGAJO "1" - "*" T_LEGAJO_ASIGNADO


@enduml
