from .LocalizacionFilter import (
    TLocalidadFilter, 
    TBarrioFilter, 
    TCPCFilter, 
    TLocalizacionFilter, 
    TLocalizacionHistoryFilter
)
from .DemandaFilters import (
    TBloqueDatosRemitenteFilter,
    TTipoInstitucionDemandaFilter,
    TAmbitoVulneracionFilter,
    TTipoPresuntoDelitoFilter,
    TInstitucionDemandaFilter,
    TDemandaFilter,
    TDemandaHistoryFilter,
    TTipoCodigoDemandaFilter,
    TCodigoDemandaFilter,
    TCalificacionDemandaFilter,
    TCalificacionDemandaHistoryFilter,
    TDemandaScoreFilter, 
    TDemandaScoreHistoryFilter,
)
from .PersonaFilter import (
    TVinculoDePersonasFilter,
    TPersonaFilter,
    TPersonaHistoryFilter,
    TInstitucionEducativaFilter,
    TEducacionFilter,
    TEducacionHistoryFilter,
    TInstitucionSanitariaFilter,
    TSituacionSaludFilter,
    TEnfermedadFilter,
    TMedicoFilter,
    TCoberturaMedicaFilter,
    TCoberturaMedicaHistoryFilter,
    TPersonaEnfermedadesFilter,
    TPersonaEnfermedadesHistoryFilter,
    TNNyAScoreFilter,
    TNNyAScoreHistoryFilter,
    TLegajoFilter,
    TLegajoHistoryFilter,
)
from .VulneracionFilter import (
    TCategoriaMotivoFilter,
    TCategoriaSubmotivoFilter,
    TGravedadVulneracionFilter,
    TUrgenciaVulneracionFilter,
    TCondicionesVulnerabilidadFilter, 
    TVulneracionFilter,
    TVulneracionHistoryFilter,
)
from .IntermediasFilter import (
    TLocalizacionPersonaFilter,
    TLocalizacionPersonaHistoryFilter,
    TDemandaPersonaFilter,
    TDemandaPersonaHistoryFilter,
    TDemandaZonaFilter,
    TDemandaZonaHistoryFilter,
    TDemandaVinculadaFilter,
    TDemandaVinculadaHistoryFilter,
    TPersonaCondicionesVulnerabilidadFilter,
    TPersonaCondicionesVulnerabilidadHistoryFilter,
)
from .EvaluacionFilter import (
    TActividadTipoFilter, 
    TInstitucionActividadFilter, 
    TActividadFilter,
    TRespuestaFilter, 
    TIndicadoresValoracionFilter, 
    TEvaluacionesFilter, 
    TDecisionFilter, 
    TActividadHistoryFilter,
    TEvaluacionesHistoryFilter
)
