from .CustomUserSerializer import CustomUserSerializer, GroupSerializer, PermissionSerializer
from .LocalizacionSerializer import TProvinciaSerializer, TDepartamentoSerializer, TLocalidadSerializer, TBarrioSerializer, TCPCSerializer, TLocalizacionSerializer
