"@startuml full_logical_erd"

' !define ENTITY
!define PRIMARY_KEY(x) <b><color:blue>x</color></b>
!define FOREIGN_KEY(x) <color:green>x</color>

hide circle
left to right direction

entity T_DEMANDA {
    + PRIMARY_KEY(id)
    --
    fecha_ingreso
    hora_ingreso
    id_notifacion_manual
    notificacion_nro
    descripcion
    ultima_actualizacion
    score = int
    score_vulneracion = int
    score_evaluacion = int
    --
    FOREIGN_KEY(T_LOCALIZACION)
    FOREIGN_KEY(T_USUARIO_LINEA)
    --
}

entity T_DEMANDA_ASIGNADO {
    + PRIMARY_KEY(id)
    --
    esta_activo = bool 'sigue en curso la verificacion / archivar=false
    recibido = bool ' casilla mail = leido/no leido
    comentarios
    --
    FOREIGN_KEY(T_USER)
    FOREIGN_KEY(T_DEMANDA)
    --
    AsignarUser(
        user.esta_activo
        )
}

entity T_PRECALIFICACION_DEMANDA {
    + PRIMARY_KEY(id)
    --
    fecha
    hora
    descripcion
    estado_demanda = (
        URGENTE,
        NO_URGENTE,
        COMPLETAR
    )
    --
    FOREIGN_KEY(T_DEMANDA on_delete=cascade null=False blank=False unique=True)
}

entity T_LOCALIZACION {
    + PRIMARY_KEY(id)
    --
    calle
    numero
    referencia_geo
    --
    FOREIGN_KEY(T_BARRIO)
    --
    ValidarConAPI(
        calle,
        numero,
        barrio,
        localidad,
        provincia
        )
}

entity T_NNyA {
    + PRIMARY_KEY(id)
    --
    --
    FOREIGN_KEY(T_NNyA_EDUCACION)
    FOREIGN_KEY(T_LEGAJO nullable=true)
    FOREIGN_KEY(T_INSTITUCION_SANITARIA)
    FOREIGN_KEY(T_VULNERACION_principal nullable=true)
    FOREIGN_KEY(T_PERSONA)
    --
    ValidarAdultoFalse(
        persona.adulto,
        persona.fecha_nacimiento
        )
}

entity T_NNyA_EDUCACION {
    + PRIMARY_KEY(id)
    --
    curso
    nivel
    turno
    comentarios
    --
    FOREIGN_KEY(T_INSTITUCION_EDUCATIVA)
    FOREIGN_KEY(T_NNyA)
    --
}

entity T_PERSONA {
    + PRIMARY_KEY(id)
    --
    nombre
    apellido
    fecha_nacimiento
    sexo
    observaciones
    adulto = bool
    --
    --
}

entity T_DEMANDA_PERSONA {
    + PRIMARY_KEY(id)
    --
    conviviente = bool
    autordv = bool
    autordv_principal = bool
    nnya = bool
    nnya_principal = bool
    --
    FOREIGN_KEY(T_DEMANDA)
    FOREIGN_KEY(T_PERSONA)
    --
}

entity T_VINCULO_PERSONA {
    + PRIMARY_KEY(id)
    --
    --
    FOREIGN_KEY(T_VINCULO)
    FOREIGN_KEY(T_PERSONA)
    FOREIGN_KEY(T_PERSONA)
    --
}

entity T_USUARIO_LINEA {
    + PRIMARY_KEY(id)
    --
    nombre
    apellido
    fecha_nacimiento
    sexo
    telefono
    --
    FOREIGN_KEY(T_VINCULO_USUARIO_LINEA)
    FOREIGN_KEY(T_INSTITUCION_USUARIO_LINEA)
    FOREIGN_KEY(T_RESPONSABLE)
    --
}

entity T_INSTITUCION_USUARIO_LINEA {
    + PRIMARY_KEY(id)
    --
    nombre
    contacto
    --
}

entity T_RESPONSABLE {
    + PRIMARY_KEY(id)
    --
    nombre
    apellido
    --
    FOREIGN_KEY(T_CARGO)
}

entity T_VULNERACION {
    + PRIMARY_KEY(id)
    --
    principal_demanda = bool
    actualidad = bool
    sumatoria_de_pesos = int    -- sumatoria de pesos de las categorias
    --
    FOREIGN_KEY(T_DEMANDA)
    NNyA = FOREIGN_KEY(T_PERSONA nnya=true nullable=false blank=false)
    AutorDV = FOREIGN_KEY(T_PERSONA autordv=true nullable=true blank=true)
    FOREIGN_KEY(T_CATEGORIA_MOTIVO)
    FOREIGN_KEY(T_CATEGORIA_SUBMOTIVO)
    FOREIGN_KEY(T_GRAVEDAD_VULNERACION)
    FOREIGN_KEY(T_URGENCIA_VULNERACION)
    --
    TriggerOnInsert(
        unique(T_DEMANDA, principal=true),
        T_DEMANDA.score_vulneracion += sumatoria_de_pesos
        T_DEMANDA.score += sumatoria_de_pesos
    )
}

entity T_ACTIVIDAD {
    + PRIMARY_KEY(id)
    --
    fecha
    hora
    descripcion
    --
    FOREIGN_KEY(T_DEMANDA)
    FOREIGN_KEY(T_ACTIVIDAD_TIPO)
    FOREIGN_KEY(T_INSTITUCION_ACTIVIDAD)
    --
}

entity T_RESPUESTA {
    + PRIMARY_KEY(id)
    --
    fecha
    hora
    mail
    mensaje
    --
    FOREIGN_KEY(T_DEMANDA)
    FOREIGN_KEY(T_INSTITUCION_RESPUESTA)
    --
    ServicioDeMailSMTP(
        mail,
        mensaje
        )
}

entity T_DEMANDA_VINCULADA {
    + PRIMARY_KEY(id)
    --
    --
    FOREIGN_KEY(T_DEMANDA)
    FOREIGN_KEY(T_DEMANDA)
    --
}

entity T_DECISION {
    + PRIMARY_KEY(id)
    --
    fecha
    hora
    justificacion = text
    decision = (
        APERTURA DE LEGAJO,
        RECHAZAR CASO
    )
    --
    FOREIGN_KEY(T_DEMANDA)
    --
    TriggerOnInsert(
        CreationOfLegajo(
            dropdown = "Apertura de legajo" || T_DEMANDA.score > 10 || T_DEMANDA.score_vulneracion > 10 || T_DEMANDA.score_evaluacion > 10
            bool = true
        )
        CreationOfMPI_MPE(
            dropdown = "Apertura de legajo"  || T_DEMANDA.score > 10 || T_DEMANDA.score_vulneracion > 10 || T_DEMANDA.score_evaluacion > 10
            bool = true
        )
        RechazarCaso(
            dropdown = "Rechazar el caso"
            bool = true
        )
    )
}

entity T_INDICADORES_VALORACION {
    + PRIMARY_KEY(id)
    --
    nombre
    descripcion
    peso = int
    --
    --
}

entity T_EVALUACIONES {
    + PRIMARY_KEY(id)
    --
    si_no = bool
    --
    FOREIGN_KEY(T_DEMANDA)
    FOREIGN_KEY(T_INDICADORES_VALORACION)
    --
    TriggerOnInsert(
        T_DEMANDA.score += T_INDICADORES_VALORACION.peso
        T_DEMANDA.score_evaluacion += T_INDICADORES_VALORACION.peso
        )
}

entity T_LEGAJO {
    + PRIMARY_KEY(id)
    --
    info_legajo
    --
    FOREIGN_KEY(T_NNyA)
    --
}

entity T_LEGAJO_ASIGNADO {
    + PRIMARY_KEY(id)
    --
    esta_activo = bool 'sigue en curso la verificacion / archivar=false
    recibido = bool ' casilla mail = leido/no leido
    --
    FOREIGN_KEY(T_USER)
    FOREIGN_KEY(T_LEGAJO)
    --
    AsignarUser(
        user.esta_activo
        )
}

entity T_USER {
    + PRIMARY_KEY(id)
    --
    nombre
    apellido
    fecha_nacimiento
    sexo
    telefono
    email
    --
    --
}

entity T_VINCULO {
    + PRIMARY_KEY(id)
    --
    nombre
    --
    --
}

entity T_CARGO {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_CATEGORIA_MOTIVO {
    + PRIMARY_KEY(id)
    --
    nombre
    peso = int
    --
    --
}

entity T_CATEGORIA_SUBMOTIVO {
    + PRIMARY_KEY(id)
    --
    nombre
    peso = int
    --
    FOREIGN_KEY(T_CATEGORIA_MOTIVO)
    --
}

entity T_URGENCIA_VULNERACION {
    + PRIMARY_KEY(id)
    --
    nombre
    peso = int
    --
}

entity T_GRAVEDAD_VULNERACION {
    + PRIMARY_KEY(id)
    --
    nombre
    peso = int
    --
}

entity T_PRIORIDAD_INTERVENCION {
    + PRIMARY_KEY(id)
    --
    peso = int
    nombre
    --
}

entity T_BARRIO {
    + PRIMARY_KEY(id)
    --
    nombre
    --
    FOREIGN_KEY(T_LOCALIDAD)
}

entity T_LOCALIDAD {
    + PRIMARY_KEY(id)
    --
    nombre
    --
    FOREIGN_KEY(T_PROVINCIA)
}

entity T_PROVINCIA {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_VINCULO_USUARIO_LINEA {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_INSTITUCION_ACTIVIDAD {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_INSTITUCION_RESPUESTA {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_INSTITUCION_EDUCATIVA {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_INSTITUCION_SANITARIA {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

entity T_ACTIVIDAD_TIPO {
    + PRIMARY_KEY(id)
    --
    nombre
    --
}

T_DEMANDA_ASIGNADO "*" - "1" T_USER
T_DEMANDA "1" - "*" T_DEMANDA_ASIGNADO
T_DEMANDA "1" -- "1" T_PRECALIFICACION_DEMANDA

T_DEMANDA "*" -- "1" T_LOCALIZACION
T_LOCALIZACION "*" -- "1" T_BARRIO
T_LOCALIZACION "*" -- "1" T_LOCALIDAD
T_LOCALIZACION "*" -- "1" T_PROVINCIA

T_NNyA "1" -- "1" T_NNyA_EDUCACION
T_NNyA_EDUCACION "*" -- "1" T_INSTITUCION_EDUCATIVA
T_NNyA "*" -- "1" T_INSTITUCION_SANITARIA

T_NNyA "1" - "1" T_PERSONA

T_DEMANDA_PERSONA "*" -- "1" T_DEMANDA
T_PERSONA "1" -- "*" T_DEMANDA_PERSONA

T_VINCULO_PERSONA "*" - "1" T_PERSONA
T_VINCULO_PERSONA "*" - "1" T_PERSONA
T_VINCULO "1" --- "*" T_VINCULO_PERSONA

T_DEMANDA "*" -- "1" T_USUARIO_LINEA
T_USUARIO_LINEA "*" -- "1" T_VINCULO_USUARIO_LINEA

T_USUARIO_LINEA "*" -- "1" T_INSTITUCION_USUARIO_LINEA

T_USUARIO_LINEA "*" -- "1" T_RESPONSABLE
T_RESPONSABLE "*" -- "1" T_CARGO

T_DEMANDA "1" --- "*" T_VULNERACION
T_CATEGORIA_MOTIVO "1" -- "*" T_CATEGORIA_SUBMOTIVO
T_CATEGORIA_MOTIVO "1" -- "*" T_VULNERACION
T_CATEGORIA_SUBMOTIVO "1" -- "*" T_VULNERACION

T_VULNERACION "*" -- "1" T_PRIORIDAD_INTERVENCION
T_VULNERACION "*" -- "1" T_GRAVEDAD_VULNERACION
T_VULNERACION "*" -- "1" T_URGENCIA_VULNERACION

T_PERSONA "1" -- "*" T_VULNERACION
T_PERSONA "1" -- "*" T_VULNERACION

T_ACTIVIDAD "*" ---- "1" T_DEMANDA
T_ACTIVIDAD "*" - "1" T_ACTIVIDAD_TIPO
T_ACTIVIDAD "*" - "1" T_INSTITUCION_ACTIVIDAD

T_RESPUESTA "*" -- "1" T_DEMANDA
T_RESPUESTA "*" - "1" T_INSTITUCION_RESPUESTA

T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA
T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA

T_DECISION "*" --- "1" T_DEMANDA
T_DEMANDA "1" -- "*" T_EVALUACIONES
T_EVALUACIONES "*" -- "1" T_INDICADORES_VALORACION

T_LEGAJO "1" - "1" T_NNyA

T_LEGAJO_ASIGNADO "*" - "1" T_USER
T_LEGAJO "1" - "*" T_LEGAJO_ASIGNADO

@enduml

' DemandasVinculadas = Conexiones de la demanda = caso1=fkDemanda, caso2=fkDemanda
' caratula = identificar legajo o expediente
' la caratula identifica el NNyA al que se le genera la demanda
' el legajo deberia estar relacionado con la caratula, ¿ osea el NNyA principal ?
