"@startuml just_entities_relationship"

' !define ENTITY
!define PRIMARY_KEY(x) <b><color:blue>x</color></b>
!define FOREIGN_KEY(x) <color:green>x</color>

hide circle
left to right direction

' ---> T_DEMANDA parent relationship
entity T_DEMANDA {
    + PRIMARY_KEY(id)
    --
    --
    FOREIGN_KEY(NNyA_principal)
    FOREIGN_KEY(VULNERACION_principal)
    --
}
T_DEMANDA_USER "*" - "1" T_USER
T_DEMANDA "1" - "*" T_DEMANDA_USER
T_DEMANDA "*" -- "1" T_ESTADO_DEMANDA

T_DEMANDA "*" -- "1" T_LOCALIZACION_DEMANDA
T_LOCALIZACION_DEMANDA "*" -- "1" Barrio
T_LOCALIZACION_DEMANDA "*" -- "1" Localidad
T_LOCALIZACION_DEMANDA "*" -- "1" Provincia

T_DEMANDA_NNyA "*" - "1" T_DEMANDA
T_NNyA "1" - "*" T_DEMANDA_NNyA
T_NNyA "1" -- "*" T_NNyA_DDV
T_NNyA_DDV "*" -- "1" T_DDV
T_NNyA "1" -- "1" T_NNyA_ESTUDIO
T_NNyA_ESTUDIO "*" -- "1" T_INSTITUCION_EDUCATIVA
T_NNyA "*" -- "1" T_INSTITUCION_SANITARIA
T_VINCULO_NNyA_ADULTO "*" --- "1" T_NNyA
T_VINCULO_NNyA_AUTORDV "*" --- "1" T_NNyA
T_VINCULO_NNyA_NNyA "*" --- "1" T_NNyA
T_VINCULO "1" --- "*" T_VINCULO_NNyA_NNyA

T_DEMANDA_ADULTO "*" -- "1" T_DEMANDA
T_ADULTO "1" -- "*" T_DEMANDA_ADULTO
T_VINCULO_NNyA_ADULTO "*" - "1" T_ADULTO
T_VINCULO "1" --- "*" T_VINCULO_NNyA_ADULTO

T_DEMANDA_AUTORDV "*" -- "1" T_DEMANDA
T_AUTORDV "1" -- "*" T_DEMANDA_AUTORDV
T_VINCULO_NNyA_AUTORDV "*" - "1" T_AUTORDV
T_VINCULO "1" --- "*" T_VINCULO_NNyA_AUTORDV

T_DEMANDA "*" -- "1" T_USUARIO_L
T_USUARIO_L "*" -- "1" T_VINCULO_USUARIO_L
T_USUARIO_L "*" -- "1" T_INSTITUCION_USUARIO_L
T_USUARIO_L "*" -- "1" T_RESPONSABLE

T_DEMANDA "1" --- "*" T_VULNERACION_DEMANDA
T_DDV "1" -- "*" T_VULNERACION_DEMANDA
' T_VULNERACION_DEMANDA_DDV "*" -- "1" T_VULNERACION_DEMANDA
' T_VULNERACION_DEMANDA_DDV "*" -- "1" T_DDV
T_VULNERACION_DEMANDA "*" -- "1" T_PRIORIDAD_INTERVENCION
T_VULNERACION_DEMANDA "*" -- "1" T_PROBLEMATICA
T_VULNERACION_DEMANDA "*" -- "1" T_AMBITO
T_VULNERACION_DEMANDA "*" -- "1" T_OPERADOR
T_NNyA "1" -- "*" T_VULNERACION_DEMANDA
' T_DEMANDA parent relationship  <---

' ---> T_DEMANDA Child Relationship (Actividad + Evaluacion + Respuesta)
T_ACTIVIDAD "*" ---- "1" T_DEMANDA
T_ACTIVIDAD "*" - "1" T_ACTIVIDAD_TIPO
T_ACTIVIDAD "*" - "1" T_INSTITUCION_ACTIVIDAD

T_RESPUESTA "*" -- "1" T_DEMANDA
T_RESPUESTA "*" - "1" T_INSTITUCION_RESPUESTA

T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA
T_DEMANDA_VINCULADA "*" - "1" T_DEMANDA
' DemandasVinculadas = Conexiones de la demanda = caso1=fkDemanda, caso2=fkDemanda

T_EVALUACION "*" --- "1" T_DEMANDA
T_EVALUACION "1" -- "1" T_VALIDACION_DATOS
T_EVALUACION "1" -- "1" T_VALIDACION_ACTIVIDADES
T_EVALUACION "*" -- "1" T_GRAVEDAD_TIPO
T_EVALUACION "*" - "1" T_URGENCIA_TIPO

T_EVALUACION "*" - "1" T_EVALUACION_ACCION
T_EVALUACION_ACCION "1" --"*" T_ACCION_TIPO

' caratula = identificar legajo o expediente
' NNyA Relationship
T_LEGAJO "1" - "1" T_NNyA
' la caratula identifica el NNyA al que se le genera la demanda
' el legajo deberia estar relacionado con la caratula


@enduml
